GET http://localhost:3333/
###
GET http://localhost:3333/api/v1/fornecedores
###
GET http://localhost:3333/api/v1/fornecedores/11
###
POST http://localhost:3333/api/v1/fornecedores
Content-Type: application/json

{
    "nome": "Mouras",
    "cnpj": "21.906.458/0001-87",
    "telefone": "84 8797-8566",
    "email": "lavinia32@hotmail.com",
    "endereco": "Chácara Paulo Barbosa, 22, Freitas do Oeste, Mato Grosso do Sul",
    "produtos": ["deleniti", "itaque"],
    "status": "inativo"
}
###
PATCH http://localhost:3333/api/v1/fornecedores/11
Content-Type: application/json

{
    "status": "ativo"
}
###
DELETE http://localhost:3333/api/v1/fornecedores/12
###
GET http://localhost:3333/api/v1/fornecedores?sort=nome
###
GET http://localhost:3333/api/v1/fornecedores?fields=produtos,nome
###
GET http://localhost:3333/api/v1/fornecedores?status=inativo
###